version: "3.8"

services:
  postgres:
    image: ankane/pgvector:latest   
    container_name: pregcare-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pregcare_user
      POSTGRES_PASSWORD: pregcare_pwd
      POSTGRES_DB: pregcare_db 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pregcare-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abiemakmal31@gmail.com
      PGADMIN_DEFAULT_PASSWORD: alamakIPPLbah321
    depends_on:
      - postgres

volumes:
  pgdata:
